[buttons]
scanEvent={C686DCEE-54F2-419E-9A27-2FC7F2E98F9E}
pdfEvent={FC4767C1-C8B3-48A2-9CFA-2E90CB3D3590}
printEvent={A6C5A715-8C6E-11D2-977A-0000F87A926F}


[common]
outputDir=C:\Scan

counter=18
; Уникальный счетчик (добавляется к имени файла)

filename=Сканирование_
; Префикс имени файла

mkdir=1
; Создавать папку вида 30 April 2013 every day

; JPGQuality = 50
; Качество JPG-файла (соотв. и размер)

; mapUsername = COMPUTER_NAME\Guest


; verboseLog =
; WIA constant default values to log-file

printerName=HPLJM2727
; Имя принтера, как оно представлено в Панели управления
; Printer name from Control Panel's "Printers and Faxes"


[WIA]
; Windows Image Acquisition constants (see WIA_Constants.txt)
; Разрешены константы WIA только с ЦИФРОВЫМИ значениями
; Only digital WIA-constant values are allowed

; 6146 = 1
; 1-color, 2-gray, 4-mono

; 6147 = 100
; 6148 = 100
; Разрешение изображения (DPI). Если распечатываете на принтере - выставьте по 300

; 6149 = 0
; X.Top
; 6150 = 0
; Y.Top

; 6151 = 8,5
; HorizontalExtent
; 6152 = 11
; VerticalExtent
; Перед тем как раскомментировать, умножьте эти значения на DPI!
; Before uncomment multiply these figures to DPI parameter values!



[events]
; События от вашего сканера, подставьте их в секцию [buttons]
{A28BBADE-64B6-11D2-A231-00C04FA31809}=Device connected (Device connected Event)
{143E4E83-6497-11D2-A231-00C04FA31809}=Device disconnected (Device disconnected Event)
{A6C5A715-8C6E-11D2-977A-0000F87A926F}=Scan/Image Button (Scan To Image - Button Press)
{9D095B89-37D6-4877-AFED-62A297DC6DBE}=Scan/OCR Button (Scan To OCR - Button Press)
{C686DCEE-54F2-419E-9A27-2FC7F2E98F9E}=Scan/E-mail Button (Scan To E-mail - Button Press)
{FC4767C1-C8B3-48A2-9CFA-2E90CB3D3590}=Scan/File Button (Scan To File - Button Press)
